### ISSUE TITLE
Proposed structure for blog posts

### ISSUE THREAD

**Issue by mersocarlin** [mersocarlin/mersocarlin.com#155]
Depends on https://github.com/mersocarlin/mersocarlin.com/issues/153

From:

```
title: 'POST_TITLE'
excerpt: 'SMALL_SUMMARY'
coverImageUrl: '/assets/blog/post-title-cover.jpg'
date: 'YYYY-MM-DDT00:00:00.000Z'
author:
  name: Hemerson Carlin
  imageUrl: '/hemerson-dark.jpg'
ogImage:
  url: '/assets/blog/post-title-og.jpg'
previousSlugs: ''
```

To:

```
title: 'POST_TITLE'
excerpt: 'SMALL_SUMMARY'
images:
  coverUrl: '/assets/blog/post-title-cover.jpg'
  ogUrl: '/assets/blog/post-title-og.jpg'
date: '2016-09-10T00:00:00.000Z'
```
